# Site settings ...
uri: masdimya.github.io
domain: masdimya.github.io
url: https://masdimya.github.io
name: masdimya
title: Welcome to my site | masdimya
email: dimas6597@gmail.com
author: Masdimya
template: Mangan
template_src: https://github.com/dikiaap/mangan
keywords: "software engineer, masdimya, dimas"
description: "I'm <b>Dimas Ikbalul Aulia</b>. Currently work as <b> Web Developer </b> at 
  <b><a href=\"https://www.elnusa.co.id/\" target=\"_blank\">🏢 Elnusa, Jakarta</a></b>
  and also taking up <b>freelance projects</b>. 
  My primary focus in <b>backend technologies</b>, and I have a keen interest in <b>software architecture</b>. 
  <br>
  <br>
  Throughout my career, I have worked extensively with popular technologies such as <b>Node.js, Vue.js, Laravel, PostgreSQL, and Redis</b>. 
  <br>
  <br>
  If you have any questions, collaboration ideas, or exciting projects, feel free to get in touch. Reach me on <b><a href=\"/contact\" >contacts </a><b>
  "
social_username: masdimya

# Build settings ...
sass:
  style: compressed
markdown: kramdown
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"
exclude:
  - README.md

# Plugins ...
plugins:
  - jekyll-paginate
  - jemoji